server:
  port: 80
  
spring:
  profiles:    include:    - db  datasource:
    url: ${db.url}
    driver-class-name: ${db.driver}
    username: ${db.username}
    password: ${db.password}
    type: com.alibaba.druid.pool.DruidDataSource